version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    networks:
      - app-network

  server:
    build:
      context: ./server 
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase?schema=public"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
